# .github/actions/setup-system-deps/action.yml
name: 'Install Python dependencies'
description: 'Installs Python project dependencies from requirements.txt and the local vega_common package.'
runs:
  using: 'composite'
  steps:
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        # Explicitly set PKG_CONFIG_PATH to help find .pc files
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH
        echo "Using PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
        # Install requirements, including PyGObject which needs the .pc file
        pip install -r requirements.txt
        # Install local package
        pip install -e ./vega_common
