name: Vega CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        uses: ./.github/actions/setup-system-deps

      - name: Check pkg-config setup
        # This step is skipped for normal runs. Set 'if: true' to enable for debugging.
        if: false
        uses: ./.github/actions/debug-libgirepository

      - name: Install Python dependencies
        uses: ./.github/actions/setup-project-deps

      - name: Run tests
        run: |
          python -m pytest

      - name: Run tests with coverage
        run: |
          python -m pytest --cov=vega_common --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8>=5.0.0 mypy>=1.0.0 black autopep8

      - name: Format code with Black
        run: |
          black vega_common vega_server vega_client --line-length 100

      - name: Check with flake8
        continue-on-error: true
        run: |
          # Use setup.cfg configuration instead of command line arguments
          python -m flake8 vega_common vega_server vega_client

      - name: Auto-fix flake8 issues (information only)
        continue-on-error: true
        run: |
          # Show how autopep8 would fix issues, but don't modify files
          autopep8 --max-line-length=100 --aggressive --aggressive --diff -r vega_common vega_server vega_client || true

      - name: Type check with mypy
        continue-on-error: true
        run: |
          python -m mypy vega_common vega_server vega_client --ignore-missing-imports
